### ISSUE TITLE
Cannot complete recipe for Storage Drawers Drawer Controller

### ISSUE THREAD

**Issue by karsen777** [Drakma/vacant-sky-3#40] opened 2019-05-17 02:12 UTC
After placing the items into a crafting table, either manually or through JEI, the finished product isn't displayed and you are unable to drag it into your inventory.

**Comment by Drakma** [comment] 2019-05-17 02:38
Caused by a bad ore dictionary.  Fixed in latest build

**Closed as completed** 2019-05-17 02:38 UTC
